[workspace]
members = [
    "crates/elitelm-backend-genie",
    "crates/elitelm-backend-genie-sys",
    "crates/elitelm-backend-llamacpp",
    "crates/elitelm-backend-llamacpp-sys",
    "crates/elitelm-core",
    "crates/elitelm-cli",
    "crates/elitelm-server",
]
resolver = "3"

[workspace.package]
edition = "2024"
license = "MIT"
rust-version = "1.95"

[workspace.dependencies]
anyhow = "1.0"
assert_cmd = "2.0"
axum = "0.8"
bindgen = "0.72"
cc = "1.2"
cmake = "0.1"
clap = { version = "4.5", features = ["derive"] }
http-body-util = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
tempfile = "3.23"
thiserror = "2.0"
libloading = "0.8"
windows-sys = { version = "0.59", features = ["Win32_System_LibraryLoader"] }
tokio = { version = "1.48", features = ["macros", "net", "rt-multi-thread", "fs", "io-util"] }
tower = { version = "0.5", features = ["util"] }
uuid = { version = "1.18", features = ["v4"] }
reqwest = { version = "0.12", features = ["blocking", "json"] }
